### ISSUE TITLE
How to get access to Varnish administration interface?

### ISSUE THREAD

**Issue by mryvlin** [drud/ddev-contrib#101]
Having the configuration as described in https://github.com/drud/ddev-contrib/tree/master/docker-compose-services/varnish, how can I access the administration interface ("built-in text-based administration interface") from within the web container?

**Comment by rfay** [comment]
Hi @mryvlin - Do you have a link to the "built-in text-based admin interface"? What port is it supposed to be on?

**Comment by mryvlin** [comment]
Hi @rfay! 
You can find it as the "-T" flag in the docs here - https://www.varnish-software.com/wiki/content/tutorials/varnish/varnish_ubuntu.html or as "Varnish-agent" in https://docs.varnish-software.com/varnish-administration-console/installation/properties/. Seems there is no unique port for that, first docs use 6082 and in the second it's 6085.
Thanks a lot for the quick support!

**Comment by rfay** [comment]
I was doing a whole PR to add -T 6082 and expose it... but all you need is to run varnishadm

`ddev ssh -s varnish` and run `varnishadm`

or

`ddev exec -s varnish varnishadm`

Let me know if that answers it for you. If you actually need the port exposed I now know how to, you just add this to the varnish section in the docker-compose:

```
    # Expose the text terminal so it can be accessed from web container
    # with `telnet varnish 6082` or `ddev exec telnet varnish 6082`
    expose:
    - "6082"
    command: '-T 0.0.0.0:6082'
```

**Comment by rfay** [comment]
Answer in https://github.com/drud/ddev-contrib/issues/101#issuecomment-733056916

Closing for now, happy to continue the conversation here or elsewhere.
