### ISSUE TITLE
docker-compose-services/postgres - does .ddev/config.yaml need to refer to postgres for when ddev start is run?

### ISSUE THREAD

**Issue by therobyouknow** [drud/ddev-contrib#108]
My config.yaml looks like:

```
name: mysite-develop
type: drupal8
docroot: web
php_version: "7.3"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.3"
mysql_version: ""
provider: default
use_dns_when_possible: true
composer_version: ""
```

But this creates a mariadb container, according to the log output displayed after I run `ddev start`

`Creating volume "ourhealthheroes-develop-mariadb" with default driver` 

So do I need to change my `config.yaml` to use a postgres db before I follow the setup instructions here: https://github.com/drud/ddev-contrib/tree/master/docker-compose-services/postgres

It seems I need to do something, because if I try to use the commands provided in the above, e.g.  `ddev pgsql_drop`  I get:

```
ERROR: No such service: postgres
Failed to run pgsql_drop : exit status 1

```

Related issue: https://github.com/drud/ddev/issues/2187

**Comment by therobyouknow** [comment]
Solution here:

Help given by Pedro Cambra - see this twitter thread - https://twitter.com/therobyouknow/status/1341833924297842691

Thanks to Pedro for his help and thanks to Randy and team for a great tool, too.

I will try to contribute to updating the docs at: https://github.com/drud/ddev-contrib/tree/master/docker-compose-services/postgres if wanted. Thank you so much again.

**Comment by rfay** [comment]
Yeah, when you use a contributed solution, you're overriding everything and you're responsible yourself for all settings. You can just delete settings.ddev.php if you want to. It's probably best to just use `ddev config --disable-settings-management` for this case.
