### ISSUE TITLE
DrupalCI ChromeDriver instructions leads to "unable to set cookie" error

### ISSUE THREAD

**Issue by damienmckenna** [drud/ddev-contrib#114]
Following the DrupalCI ChromeDriver documentation lead me to the following error when I ran the suggested example test:

`$ phpunit --verbose -c core/phpunit.xml core/modules/system/tests/src/FunctionalJavascript/System/DateFormatTest.php
PHPUnit 8.5.8 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.25-1+0~20201130.73+debian10~1.gbp042074
Configuration: /var/www/html/core/phpunit.xml

Testing Drupal\Tests\system\FunctionalJavascript\System\DateFormatTest
E                                                                   1 / 1 (100%)

Time: 14.39 seconds, Memory: 4.00 MB

There was 1 error:

1) Drupal\Tests\system\FunctionalJavascript\System\DateFormatTest::testDateFormatXss
Exception: unable to set cookie
  (Session info: headless chrome=74.0.3729.157)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 4.19.76-linuxkit x86_64)

/var/www/html/vendor/instaclick/php-webdriver/lib/WebDriver/Exception.php:144
/var/www/html/vendor/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php:157
/var/www/html/vendor/instaclick/php-webdriver/lib/WebDriver/Session.php:191
/var/www/html/core/tests/Drupal/FunctionalJavascriptTests/DrupalSelenium2Driver.php:43
/var/www/html/vendor/behat/mink/src/Session.php:212
/var/www/html/core/tests/Drupal/Tests/UiHelperTrait.php:438
/var/www/html/core/tests/Drupal/Tests/UiHelperTrait.php:326
/var/www/html/core/tests/Drupal/Tests/UiHelperTrait.php:250
/var/www/html/core/modules/system/tests/src/FunctionalJavascript/System/DateFormatTest.php:33
/var/www/html/vendor/phpunit/phpunit/src/Framework/TestResult.php:691

ERRORS!
Tests: 1, Assertions: 5, Errors: 1.
`

This is running against Drupal 9.1 with ddev 1.16.2 running PHP 7.3, MariaDB 10.3 and the default nginx-fpm webserver.

Any suggestions?

**Comment by rfay** [comment]
@heddn any words of wisdom? (@heddn is the author of [drupalci-chromedriver recipe](https://github.com/drud/ddev-contrib/tree/master/docker-compose-services/drupalci-chromedriver), see bottom)

**Comment by damienmckenna** [comment]
I had customized the phpunit.xml file so used it, but at Bobby's suggestion used the .dist file. That didn't make any difference.

**Comment by heddn** [comment]
I haven't seen that error before. Not sure what to suggest.

**Comment by damienmckenna** [comment]
I managed to get this working, it ended up being a combination of PEBCAK and a minor note that ought to be in the documentation which I'll submit a patch for shortly. Thank you all for the help.

**Comment by Gonzalo2683** [comment]
Hello @damienmckenna, how did you solve the problem? I would really appreciate it.

**Comment by rfay** [comment]
I think his PR is https://github.com/drud/ddev-contrib/pull/118 - Please review it as you work through this, it can get in faster that way.

**Comment by damienmckenna** [comment]
@Gonzalo2683: Like @rfay says, I worked out a few things I'd done wrong, so worked on PR #118 to point out some things to others.

Ultimately the main problems were that a) I was customizing the phpunit.dist.xml file instead of just using the one out of the box, and b) had to turn off my other ddev instances. I haven't tested rfay's suggested improvements yet, which could avoid the second problem, I'm hoping to do that this week.
