### ISSUE TITLE
Support for Symfony console

### ISSUE THREAD

**Issue by alechko** [drud/ddev-contrib#115]
Hi, I have created a super simple custom command to support Sympfony console by using `ddev console ...`, this makes super easy to execute Symfony console commands without ssh into the container.

I believe that other people might find it handy so I wanted to see if it's worth submitting it here as well.

Command file path:
`commands/web/console`

Command script:
```
#!/bin/bash

## Description: Run Symphony console
## Usage: console <command>
## Example: "ddev console about" or "ddev console debug:config"
bin/console $@
```

If approved, I've already forked this repo and can submit a PR.

![Screen Shot 2021-01-29 at 09 59 27](https://user-images.githubusercontent.com/1391846/106247786-b3c98e00-6218-11eb-9ca8-834f97c737c0.png)

**Comment by rfay** [comment]
Of course, and thank you. You don't have to open an issue first, just do the PR.

Please make sure to follow the existing examples, put your name and a link at the bottom, and add the new item to the top-level README.

**Comment by alechko** [comment]
Thanks, I wasn't sure if I need to open an issue here because this branch does not have a Contributing guide, so I followed the [ddev](https://github.com/drud/ddev/blob/master/CONTRIBUTING.md) which starts with creating an issue... Anyway, the PR was submitted.
