### ISSUE TITLE
MongoDB solution no longer working

### ISSUE THREAD

**Issue by Chibby** [drud/ddev-contrib#120]
Hello,

I have set up mongodb in ddev at around November last year without issues. However, today I was trying to use this set up in a new project, and I could not get it to work at all; I keep running into this error:
Fatal error: Uncaught Error: Class 'MongoDB\Driver\Manager' not found in /var/www/html/public_html/vendor/mongodb/mongodb/src/Client.php:116

I have tried all variants of the setup as can be found in the history for the mongodb solution, but none helped.
I am also not sure whether this is an issue here, with ddev, or with the php-mongodb package.

**Comment by rfay** [comment]
Hi @Chibby - It looks like you have a problem in your code (Missing or invalid MongoDB stuff)?  The recipe doesn't tell you how to set up your code. Have you run `ddev composer install`? Did you `ddev composer require mongodb/mongodb` ?

Anyway, AFAICT this doesn't have anything to do with ddev, but it's a problem with your code.

**Comment by Chibby** [comment]
I can see the confusion. The mongodb/mongodb package is installed and working, that is not the issue.

MongoDB\Driver\Manager is part of the PECL mongodb extension that the ddev recipe is supposed to add, and I quote, "by adding `webimage_extra_packages: [php-mongodb]` to your .ddev/config.yaml."

My issue is that the mongodb extension is no longer loading.
When I `php -m` in the terminal (after `ddev ssh`) I can not find the mongodb extension listed.
Like I said, I am unsure whether this is an issue here, with ddev, or with the php-mongodb package. I am, however, sure this is not a coding issue.

**Comment by rfay** [comment]
It looks like the technique changed with php8.0. You can just change to `webimage_extra_packages: [php7.3-mongodb]` (or use the php version you want). Could you please do a PR to fix this recipe? You can just do it by editing the file on github if you want.

**Comment by Chibby** [comment]
Thanks for the answer. Verified how this works now and added expanded explanation in PR #122
