### ISSUE TITLE
general_log script is not working

### ISSUE THREAD

**Issue by dev-sukhjinder** [drud/ddev-contrib#133]
I have copied the file general_log into my project's .ddev/commands/db and then I have restarted ddev. Afterwards I run following command in my project folder 

`ddev general_log`

I got the following message

```

Enabling general_log mysql: [Warning] Using a password on the command line interface can be insecure.
✓
Press CTRL+C to exit.

Failed to run general_log : exit status 1


```

**Comment by rfay** [comment]
@jonaseberle could you take a look please?

**Comment by rfay** [comment]
@jonaseberle I think the filename is incorrect. You have `tail -f /var/lib/mysql/www.log`, but the actual log set up (with mariadb anyway) is based on the hostname. So it should be `tail -f "/var/lib/msyql/$(hostname).log"` right?

**Comment by jonaseberle** [comment]
@rfay you are right. I thought it was always `www.log` but that's only the case if the project name starts with `www.`...

Normal (no `.` in hostname)
```
$ ddev exec -s db hostname
my-drupal9-site-db
 
$ ddev mysql <<< 'SHOW VARIABLES LIKE "general_log_file"'
general_log_file        my-drupal9-site-db.log
```

Edge case:
```bash
$ ddev exec -s db hostname
www.ratbacher.de-db

$ ddev mysql <<< 'SHOW VARIABLES LIKE "general_log_file"'
general_log_file        www.log
```

I'll just add a 
`mysql -uroot -proot <<< "SET GLOBAL general_log_file='general_log.log'"`
in there. It's not 100% clean but I think we can assume that we are the only consumer of that setting...
