### ISSUE TITLE
Superfluous ports line in varnish recipe & trouble on Docker 3.5.0+

### ISSUE THREAD

**Issue by HeineDeelstra** [drud/ddev-contrib#144]
The ports statement on https://github.com/drud/ddev-contrib/blob/master/docker-compose-services/varnish/docker-compose.varnish.yml#L31 causes the container to fail starting on Docker 3.5.0 / WSL2 with the message:

```
'services.varnish.ports must be a list'
```

Removing the ports statement as recommended by rfay solved the issue.

**Comment by rfay** [comment]
BTW @HeineDeelstra this happens when the experimental Compose V2 is turned on in Docker Desktop. 

They're doing a canary thing, so it may have been enabled by them and not you.
