### ISSUE TITLE
SSH not working on Win10

### ISSUE THREAD

**Issue by tyler36** [drud/ddev-contrib#198]
I'm trying to follow the [SSH setup](https://github.com/drud/ddev-contrib/tree/master/recipes/sshd) on a Win10 PC.

When I run the command, I am prompted for a password, but I always get a denied error. 

```shell
ssh -p 2222 -o StrictHostKeyChecking=no localhost
lost\user13@localhost's password: 
Permission denied, please try again.
```
 
If I try `ssh-add`, the password is accepted.

I have it working in WSL though I think it might there might be an issue with Win10?

OS: Win10
DDEV: 
Win10 DDEV `1.18.2`, `1.19.0-alpha3`
WSL: `1.19.0-alpha3`

**Comment by tyler36** [comment]
Ahhh .... Win10 was sending a [Down-Level Logon Name](https://docs.microsoft.com/en-in/windows/win32/secauthn/user-name-formats)

- Win10
```shell
$ whoami 
lost\user13

$ ssh -p 2222 -o StrictHostKeyChecking=no localhost
lost\user13@localhost's password: 
Permission denied, please try again.
```

- But WSL only sends the username
```shell
$ whoami
user13

$ ssh -p 2222 -o StrictHostKeyChecking=no localhost
Enter passphrase for key '/home/user13/.ssh/id_rsa':
```

So, I need to specify the username when I run from Win10:

```shell
$ ssh -p 2222 -o StrictHostKeyChecking=no user13@localhost
user13@example-web:~$ 
```

Also confirmed: updating my Win10 SSH `~/.ssh/config` file, I can connect to the DDEV box via VSCode `Remote: SSH` extension

```
Host ExampleDDEV
    HostName localhost
    Port 2222
    StrictHostKeyChecking OFF
    User user13
```

**Comment by tyler36** [comment]
PR was submitted to help others with similar issue.

**Comment by rfay** [comment]
Nice work!

**Comment by rfay** [comment]
Could you retitle this issue to make it more search friendly, say more about what "not working" meant in the title?
