### ISSUE TITLE
Confusing Laravel example at docker-compose-services/redis

### ISSUE THREAD

**Issue by Hans4221** [drud/ddev-contrib#201]
The information for the laravel .env file should be

CACHE_DRIVER=redis
REDIS_HOST=ddev-<DDEV_SITENAME>-redis
REDIS_PASSWORD=null
REDIS_PORT=6379

and not

CACHE_DRIVER=redis
REDIS_HOST=ddev-<DDEV_SITENAME>:6379
REDIS_PASSWORD=null
REDIS_PORT=6379

**Comment by rfay** [comment]
@Hans4221 Thanks for the report and for paying attention! You can just do a PR if you know how to do it better :)

**Comment by rfay** [comment]
@Hans4221 please review 
* #202
