### ISSUE TITLE
Drupal Login broken after ddev 1.19.0 update

### ISSUE THREAD

**Issue by bserem** [drud/ddev-contrib#206]
Latest version of ddev breaks `ddev login` custom command.

Line https://github.com/drud/ddev-contrib/blob/a2bd26946993016e42f67bd73e88e646e1e5a3d4/custom-commands/drupal-login/login#L10
does not assign the value to the variable anymore, but it prints the output of `ddev drush uli` to the terminal.

**Comment by rfay** [comment]
It looks like all output is not capturable, not going to stdout/stderr. I imagine this is a regression in docker-compose, there are several issues there about it, but it's baffling. Doesn't have to do with drush. Any web command is being output unconditionally and not ending up on stdout. I'll open an issue in ddev.

**Comment by rfay** [comment]
Would love to have you test https://github.com/drud/ddev/pull/3689 - can test it with gitpod there if you want.

**Comment by bserem** [comment]
Fixed in 1.19.1, thanks
