### ISSUE TITLE
Update multisite recipe for DDEV-Local 1.13.0 (disable-settings-management)

### ISSUE THREAD

**Issue by wizonesolutions** [drud/ddev-contrib#40]
It may be possible to improve the multisite recipe using `--disable-settings-management`. However, there are some cases where it relies on ddev-generated settings. I'm not sure if ddev should maybe have a way to manually trigger generation of CMS settings files while still keeping settings management otherwise-disabled? It would be useful for one-time templating and customization like in this example.

If not, then we can either just leave it alone or expand it to include the necessary settings files.

**Comment by rfay** [comment]
Thanks so much for raising this. I was afraid I'd forget about it :)

**Comment by amitaibu** [comment]
Hi folks :wave: 

I was directed here from https://github.com/drud/ddev-contrib/pull/42#pullrequestreview-357751613

I'm not familiar with `--disable-settings-management`. What is it supposed to do? (Once I get it, maybe I could provide the docs for it :smile: )

**Comment by rfay** [comment]
From https://github.com/drud/ddev/releases/tag/v1.13.0

> If you have a complex setup and do not want ddev to manage your CMS settings files, you can now use disable_settings_management: true in your config.yaml (or ddev config --disable-settings-management) People used to have to use the "php" project type to accomplish this, but this is probably a better approach.
