### ISSUE TITLE
Cron configuration overwrites default post-start hooks

### ISSUE THREAD

**Issue by tomasnorre** [drud/ddev-contrib#58]
When using the example below, my post-start hooks from my `config.yml` is overwritten by the ones from https://github.com/drud/ddev-contrib/blob/master/recipes/cronjob/config.cron.yml

I expected these to be usable in parallel.

If I add the ones from `config.cron.yml` to my `config.yml` there are all executed as expected.

Did I overlook something in the configuration?

**Comment by rfay** [comment]
To see what the merged hooks look like, use `ddev debug configyaml`

My experience is the same as yours - the add-on config.*.yaml overwrites the post-start hook. I guess it's not unexpected. Somebody has to win probably.  The entire post-start section is won by the addon. If you had a post-stop or pre-something, those don't conflict and get merged as expected.

(It's not clear what "the example below" is, but the behavior is as you describe)

**Comment by tomasnorre** [comment]
With the example below, I meant the link. 
But you description matched my case.  I would have expected them to be merged though. 

Thanks for your reply. I can accept having them in the default `config.yml` no big deal , it's not like it's a lot of extra lines.

**Comment by rfay** [comment]
You can also include in your config.cron.yaml (or whatever) all the hooks you want, and it will work out fine. Sounds like you have a way to go with it.

**Comment by tomasnorre** [comment]
Thanks. Found a solution that worked out for me.
