### ISSUE TITLE
Service postgres user

### ISSUE THREAD

**Issue by ecosmox36** [drud/ddev-contrib#61]
not a Bug but a question: 

The  "ddev pgsql_import" is not working because the user postgres dosnt exists and the command psql ist unavailable  (the user and the commant exists inside the postgres container only)
if i fire up the command:

No passwd entry for user 'postgres'
Failed to run pgsql_import : exit status 1

did I miss something here? 

importing the database inside the postgres container now :)

**Comment by rfay** [comment]
I think you probably put the pgsql_import command inside .ddev/commands/host instead of in .ddev/commands/postgres, because the user and pgsql certainly exist in the postgres container, as you confirm.  The `ddev pgsql_import` command runs inside the postgres container.

**Comment by ecosmox36** [comment]
Yes your right, i copied the command files not the hole directory, my fault 
thanks for fast response and clarify
