### ISSUE TITLE
Mongodb suggestion: install php extension via webimage_extra_packages config option

### ISSUE THREAD

**Issue by binary-data** [drud/ddev-contrib#69]
The README suggests installing mongodb php extension by altering web image Dockerfile.

Although there is an alternative way: via config.yml. There is an option `webimage_extra_packages: [php-mongodb]`, which doesn't require to change Dockerfile. This might seem a bit cleaner.

Here is the reference: https://ddev.readthedocs.io/en/stable/users/extend/customizing-images/

**Comment by rfay** [comment]
That's correct, do you want to do a PR? It does completely change the recipe, and you're right about the approach.

**Comment by binary-data** [comment]
Sure. It shouldn't change the recipe dramatically though. And I'll need some time to actually test it.
