### ISSUE TITLE
Need a setup guide for Behat for Drupal8 with Docker DDEV

### ISSUE THREAD

**Issue by DC-Erok** [drud/ddev-contrib#72]
Need a step by step guide for setting up Behat for Drupal 8 in a Dockere + DDev enviroment

**Comment by DC-Erok** [comment]
[Setup Behat for Drupal8 with Docker DDEV.docx](https://github.com/drud/ddev-contrib/files/4746737/Setup.Behat.for.Drupal8.with.Docker.DDEV.docx)

**Comment by rfay** [comment]
Please open a PR with the changes.
